---
abstract: 'Slide Shows in Vim'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Vroom
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  File::HomeDir: '0'
  IO::All: '0'
  Template::Toolkit::Simple: '0'
  Term::Size: '0'
  YAML::XS: '0'
resources:
  bugtracker: https://github.com/ingydotnet/vroom-pm/issues
  homepage: https://github.com/ingydotnet/vroom-pm
  repository: https://github.com/ingydotnet/vroom-pm.git
version: '0.37'
