--- 
abstract: ~
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.670
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Vroom
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Field: 0
  File::HomeDir: 0
  IO::All: 0
  YAML::XS: 0
  perl: 5.6.1
version: 0.13
