---
abstract: 'Slide Shows in Vim'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Vroom
no_index:
  directory:
    - inc
    - t
requires:
  Class::Field: 0
  File::HomeDir: 0
  IO::All: 0
  Template::Toolkit::Simple: 0
  YAML::XS: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.22
